# Permalinks
# permalink:        pretty
permalink: /:title/
relative_permalinks: true

markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: [smart]

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Setup
title:            Title in config
tagline:          Tagline in config
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Nick
  url:            http://nichoth.github.io/
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/nichoth/poole
