# Permalinks
# permalink:        pretty
permalink: /:title/
relative_permalinks: true

markdown: redcarpet
highlighter: pygments

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
